### ISSUE TITLE
Full support of quoting tweets

### ISSUE THREAD

**Issue by Oire** [Oire/TheQube#58]
Now only the proper reading of quoted tweets is supported. What we need, however, is the full support that would allow users to quote selected tweets.

**Comment by Oire** [comment]
for now everything seems to be implemented correctly. However, for some reason tweets quoted by TheQube are still reported as simple links to statuses like `https://twitter.com/statuses/1234567890`. @manuelcortez, maybe you have any ideas?

**Comment by manuelcortez** [comment]
For reading quoted Tweets you still have to extract the Tweet ID, then use that id to get the full tweet object and you will have two tweets, the quoted and the original tweet. then it depends how you want to implement display in the buffers. In the TWblue repository there are some utilities for dealing with quoted tweets in src/long_tweets/tweets.py, and about quoted tweets' display, the files are src/twitter/compose.py and src/sessionmanager/session.py. Can't remember the function's name, but you can look for "quoted" or something like that.

**Comment by manuelcortez** [comment]
probably I misunderstood something. If you want to quote a tweet, you have to create an URL like https://twitter.com/username/status/xxxxxx. In your example there is not the username in the URL.

**Comment by Oire** [comment]
@manuelcortez, no no, I have no problem _reading_ them, I have problems _posting_ them. Say, you've written a cool tweet. I want to quote you. In TheQube (in Git tip) it's now possible with Ctrl+Shift+Win+Q. However, I still get plain links instead of my `qt` tweets (when reading, I prefix quoted tweets with `qt` analogously to `rt` for retweets). Thanks!

**Comment by manuelcortez** [comment]
I have fixed that thing. Wait for a pull request.
