### ISSUE TITLE
Unable to get API calls count

### ISSUE THREAD

**Issue by Oire** [Oire/TheQube#62]
In TheQube there's no way to get the rate limit. **Ctrl+Win+A** for some reason doesn't work.

**Comment by craigbrett17** [comment]
@Oire what's the procedure for me getting my fix in for things like this? Do I raise it as a pull request or do you pull in things from other people's repos? I'm not sure what the project's way of working is on that level.

**Comment by Oire** [comment]
@craigbrett17, just do a pull request, and I'll review and merge it.

**Comment by Oire** [comment]
Closing via #66.
