### ISSUE TITLE
Can't post anything on twitter

### ISSUE THREAD

**Issue by sanslash332** [Oire/TheQube#63]
Hello,
The client itself is working fine (the last version in the webpage, not the last build of the repo) can retrieve any tweet, can create buffers, can validate and get the apiKey for new sessions, but the main and important bug, is that you can't post anything. 
Anything. A new tweet, a new dm, a reply, etc. When you open the window to write the tweet all is fine, but when you press enter to send the tweet (or the corresponding accept / ok button) the tweet isn't sent, and the windows blink one time. It closes, an reopen at a time, keeping the tweet that you're writed.

It happens with two different accounts.
Thanks.

**Comment by Oire** [comment]
Thanks, fixed in 0958087d7abb56e8f7560826dad6a7ef5739c11f.
