### ISSUE TITLE
Many tweets are truncated

### ISSUE THREAD

**Issue by tmthywynn8** [Oire/TheQube#67]
I notice that many tweets. especially if they are long replies, are now being truncated when reading tweets with The Qube. It of a format similar to:
This is a tweet, and it is truncat… https://twitter.com/i/web/status/<numbers>

Not sure if there's a possibility of fixing this, but I figure I'd report it just in case. I'm using The Qube commit e19fc16,though I'm sure it exists among earlier versions as well.

**Comment by Oire** [comment]
Thanks for your report! This is confirmed and will be fixed as soon as
possible.

**Comment by manuelcortez** [comment]
Hi,

I think [this article](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets) may be useful. Basically you can request for "extended tweets" in the API calls (by passing mode="extended"). Twitter will send you tweets with another key, "full_text", wich will contains the not trunkated version of the tweet.

**Comment by Oire** [comment]
@manuelcortez, thanks! As far as I understand, I need to check whether that key exists, and if it is not there, provide usual tweet text, am I right?

**Comment by manuelcortez** [comment]
Yea, that's true. If tweet.has_key("full_text") == False, then displays the normal tweet text. Also, take into account that you can find tweets like tweet["retweeted_status"]["full_text"] provided by the API
