### ISSUE TITLE
Theqube can't get token access 

### ISSUE THREAD

**Issue by kaveinthran** [Oire/TheQube#69]
I am using win 8.1 and theqube latest with administrater previliges 

When I open theqube after first time install, it says that can't get the token access, contact the developers.

Do mention which files are needed to trace the glitch.

thanks

**Comment by Oire** [comment]
1. Did you erase your previous `%AppData%\TheQube` folder? If not, this needs to be done first.
2. Have you some quirky firewall/antivirus installed? In any case, you need to add theqube.exe in your firewall exceptions.
3. If this does not help, please attach your `%AppData%\TheQube\error.log` or send it to me directly.

**Comment by kaveinthran** [comment]
done, all working perfectly
