### ISSUE TITLE
cannot get theqube to open/run

### ISSUE THREAD

**Issue by yvonne625** [Oire/TheQube#70]
Hello,
I cannot get theqube to work on my updated windows 10. I have installed and reinstalled a few times with no luck. If I run the compatibility it will half run when I say it was running in windows 7. I can send tweets but the tweets that I can read are a year old, but I hear tweets coming in.
Also is there a way you can add me to the mailing list please? Somehow I entered my password incorrectly the second time and now it will not allow me to try again. my email is yvonne625@verizon.net and you can make my password theqube and I can figure out how to change it later.
Thanks for any help you can give me, I was so, so  happy when I read the qube was back - I missed it so very much!!! I am keeping my fingers crossed that I will be able to use the full updated version of theqube.
Thanks,
Yvonne

**Comment by Oire** [comment]
@yvonne625, Hi Yvonne! first of all, please unload TheQube and completely erase your `TheQube` folder in the application data. To do this:

1. Press **Windows+R**.
2. Type `%AppData%` (with the percent signs, exactly as I wrote) and press **Enter**.
3. Locate TheQube folder.
4. Press **Delete** or **Shift+Delete**, which of these suits you best. Confirm folder removal.

Relaunch TheQube and re-authorize your Twitter session.  
As we are on a free plan at groups.io, I can't directly add you to the list, so I've sent you an invitation, please accept it.  
Thank you, I really appreciate you like TheQube so much :)!

**Comment by yvonne625** [comment]
Hi,
Thank you so much, it worked! One more question, when I do ctr + win + home that used to take me to the top of the new tweets, but it does nothing now - is that correct? ctr + win + pg up moves up about a minute (okay sorry I did not read the whote read me, I'm working on it, but just got so frustrated, and now I am behind on a class so thought I would ask) Also I just wanted to say the scheduling of tweets is awesome, amazing and can you tell I love it, I did read  some of the read me. :)
And thanks for adding me to the email list.
Yvonne

**Comment by Oire** [comment]
Yvonne, it's now **Alt+Win+Home**, to be consistent with new moving commands.

**Comment by yvonne625** [comment]
thanks
