### ISSUE TITLE
TheQube unable to get access token for twitter. 

### ISSUE THREAD

**Issue by RunningLeopard2** [Oire/TheQube#73]
Greetings all. I am currently using TheQube 0.91 on a windows 10 4 bit system. I have managed to install the program, but when I try and authorise twitter, it simply says "something went wrong, please cal the developers.
Does anyone know how this can be fixed?

**Comment by Menelion** [comment]
Thanks for your report! On 64-bit systems please use [version 0.9.2](http://theqube.oire.org/files/bin/TheQube-0.9.2-setup.exe).
