### ISSUE TITLE
app can't start, token  not retrieved

### ISSUE THREAD

**Issue by abdullah5490** [Oire/TheQube#80]
why is it not opening at all? it said, "token not retrieved, please call the developer".

**Comment by Menelion** [comment]
What version do you use?

**Comment by abdullah5490** [comment]
I’m using the latest available, 0.9.1.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Menelion** [comment]
Please try [0.9.2](https://theqube.oire.org/files/bin/TheQube-0.9.2-setup.exe).

**Comment by abdullah5490** [comment]
Yes, this one is working. Why it is not present on theqube.oire.org?

**Comment by Menelion** [comment]
Because I should have updated the thing long time ago, and I hope to do so, but no estimate so far, sorry.
